services:
  # nginx
  web:
    build:
      context: ./frontend
      target: production
    ports:
      - 9000:80  
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    restart: always  
  app:
    build:
      context: ./app
    # volumes:
    #   - ./app:/app
    volumes:
      - /var/www/html/vendor
      - ./app:/var/www/html

  db:
    image: mysql:8.0
    volumes:
      - "./db:/docker-entrypoint-initdb.d/:rw"  
    # ports:
    #   - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: scandiweb
      MYSQL_DATABASE: scandiweb
      MYSQL_USER: scandiweb
      MYSQL_PASSWORD: scandiweb

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
  # php
  # mysql
  # redis
